# Generated by Django 3.0.5 on 2020-04-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('var_type', models.CharField(choices=[('core', 'core'), ('global', 'global'), ('server', 'server'), ('private', 'private')], default='server', max_length=7)),
                ('value_string', models.TextField()),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
    ]
