# Generated by Django 3.0.5 on 2020-04-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atropos_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('name', 'owner_id')},
        ),
    ]
