# Generated by Django 3.0.5 on 2020-04-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atropos_db', '0002_auto_20200424_1644'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('name', 'owner_id', 'var_type')},
        ),
    ]
