#!/usr/bin/env python3
import os
from lark import Lark
from dicelang import kernel
from dicelang import grammar
from dicelang import datastore

class Interpreter(object):
  def __init__(self):
    self.parser = Lark(grammar.raw_text, start='start', parser='earley')
    try:
      vars_directory = os.environ['DICELANG_DATASTORE']
    except KeyError:
      vars_directory = 'vars'
    public_path = f'{vars_directory}{os.path.sep}public'
    server_path = vars_directory
    private_path = vars_directory
    
    if not os.path.isdir(vars_directory):
      os.mkdir(vars_directory)
    
    self.public = datastore.DataStore(public_path)
    self.server = datastore.OwnedDataStore(server_path, 'server')
    self.private = datastore.OwnedDataStore(private_path, 'private')
    
    self.visitor = Visitor(self.public, self.server, self.private)
    
  def save(self):
    self.public.save()
    self.private.save()
    self.server.save()
  
  def execute(self, command, user, server):
    '''Passes the abstract syntax tree generated by the parser to the
    interpreter kernel with the user's name and the server's name for
    variable retrieval and emplacement. The result is stored in the
    variable known as `_`. The private `_` is intended to be the last
    result by that user, the server `_` is intended to be the last result
    on that server, and the public `_` is intended to be the last result
    by any command passed to the interpreter.'''
    tree = self.parser.parse(command)
    out = self.walk(tree, user, server)
    self.private.put(user, '_', out)
    self.server.put(server, '_', out)
    self.public.put('_', out)
    return out

